### PR TITLE
Remove the limit of 10 items when displaying

### PR DESCRIPTION
**Pull request by Meroje**
We'll take care of paginating when it becomes a problem

### CODE REVIEW

**Comment by smeeckaert** [comment]
It would be better in a config file, no ?

**Comment by Meroje** [comment]
I can't see a reason to limit, it should display all or paginate (items per page may be a config, or enhancer data). Right now I would rather get a simple fix though

**Comment by smeeckaert** [comment]
Fair enough

**Comment by shaoshiva** [comment]
:+1: but we need to implement pagination quickly.

**Pull request merged**
